### ISSUE TITLE
Roadmap / ToDos Overview

### ISSUE THREAD

**Issue by jannydiamond** [jannydiamond/react-mastermind#1]
- [ ] Basic Setup (create-react-app)
- [ ] Plan logical structure
- [ ] Include styled components
- [ ] Write basic components
- [ ] Include redux

**Needed Functions**
- [ ] start game / initialize game
- [ ] generate code of 4 colors
- [ ] get user input
- [ ] validate user input
- [ ] set tokens for correct answers (black/white)
- [ ] jump to next row
- [ ] check if last row
- [ ] show result
